server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code007
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

userImageFilePath: D://userImages/

articleImageFilePath: D://articleImages/